language: node_js
node_js:
- '8'
script:
- npm install
- npm test
- npm run build
notifications:
  slack:
    secure: WsZPAg15afwqx2ZIjyziLMAneBAu3m5PKR6iRFRmZt2CuRMYhW03NtipNzdJv4I+xYNO+/wAqkCnQXu54ZBqHB/O4eWkCGzRTgBcvvZ53jJwYWYDO7V3c6hePJxFnNlxbAJjApYo+eQpzlSYemZb863TfBJHqFcqPA2RzfFdFFlcjFA7j2/b/73N+ZrXJgqULJUryixhKs7iY9G309dahnZUWbmDodjp15W7FcoM998cPPuCm1T2uZgEwkgNpajmQdmPUioj2Ff6e4Gi3MMp0yBeqo+tTM6NKwBS8taIFqQUByM8ZTcIHhnCQlEUvS5dz45pqmEBIVw5rceb0qa+i5ggv0u3KB7tQdEulpnWt6g15DCT8I73o/gdNu92dEFj8VwrnpDsz58XHPdo4g6/Jz5geh8cxXOegbHJMBgKDohaO+MLsmDT/HuFP4pvgu0f0XNoMRznwmPpw3UZxOFP6w7wnwscyvHGeiPL4WpTWe2n0XCoIitUppp1bxH9V1rNYvPVvqTrZeV6Rg2TRRBwri1Fz8LxheB9P2pzOPJzfWokr2WHnG6jpyTCj112aj1EU6YwAbJE0pGAaCxO30EveMfYnur+l183SWZeEZxGqc/TkB4kpmbiDKnw+9UwVYkAc+ux5Qv7FjisNryZ4IX8oeucPqMEPHZtDFxr5k8pLiY=
